// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDGD4aC0Swi2R304HPHyCHk0RWZI2YhzI',
    appId: '1:567481575985:web:13d88cb0d1c249f14a4310',
    messagingSenderId: '567481575985',
    projectId: 'horoscope-app-1c4c0',
    authDomain: 'horoscope-app-1c4c0.firebaseapp.com',
    storageBucket: 'horoscope-app-1c4c0.firebasestorage.app',
    measurementId: 'G-C0NVXX9HG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAzg39_qXoGTS_nfR8W2KCjaToBWifstI',
    appId: '1:567481575985:android:50cd40e19a28bab34a4310',
    messagingSenderId: '567481575985',
    projectId: 'horoscope-app-1c4c0',
    storageBucket: 'horoscope-app-1c4c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6KcL7TMkVN3Sn0N_ERSxlmAQPtTnWXIc',
    appId: '1:567481575985:ios:739a91c65e7a25cd4a4310',
    messagingSenderId: '567481575985',
    projectId: 'horoscope-app-1c4c0',
    storageBucket: 'horoscope-app-1c4c0.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6KcL7TMkVN3Sn0N_ERSxlmAQPtTnWXIc',
    appId: '1:567481575985:ios:739a91c65e7a25cd4a4310',
    messagingSenderId: '567481575985',
    projectId: 'horoscope-app-1c4c0',
    storageBucket: 'horoscope-app-1c4c0.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDGD4aC0Swi2R304HPHyCHk0RWZI2YhzI',
    appId: '1:567481575985:web:c30a84e7dbdcf6cd4a4310',
    messagingSenderId: '567481575985',
    projectId: 'horoscope-app-1c4c0',
    authDomain: 'horoscope-app-1c4c0.firebaseapp.com',
    storageBucket: 'horoscope-app-1c4c0.firebasestorage.app',
    measurementId: 'G-HYJHC2NL4P',
  );
}
